id = deeprows
name = Deeprows Sports TV
mainURL = https://deeprowss.com

allowSubdomains = true
requireDoubleBackToExit = true

enableExternalLinks = true
openExternalLinksInBrowser = false
confirmOpenInBrowser = false

allowOpenMobileApp = true

JSEnabled = true
JSCanOpenWindowsAutomatically = true

DomStorageEnabled = true
DatabaseEnabled = true

AllowFileAccess = true
AllowFileAccessFromFileURLs = true

forceLandscapeMode = false

showDetailsOnErrorScreen = false
confirmOpenExternalApp = false

blockLocalhostRequests = true

trustUserCA = false

geolocationEnabled = false
cameraEnabled = true
microphoneEnabled = true

allowMixedContent = false

cacheMode = default

fadeInDuration = 400

edgeToEdge = false

deeplink = deeprowss.com
